name: Publish superset to GitHub Container Repository
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
jobs:
  build:
    env:
      DOCKER_IMAGE: superset
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: Dockerfile.${{ env.DOCKER_IMAGE }}
